amorenoz/ovs-dbg

- .github/workflows/ci.yml
> Add minimalistic ci

- .github/workflows/ci.yml
- Pipfile
- pyproject.toml
- setup.cfg
> Fix ci scripts

- .github/workflows/ci.yml
- Pipfile
- ovs_dbg/flows.py
- pyproject.toml
- setup.cfg
- tests/test_flows.py
> flows: add basic flow key value parser

- Pipfile
- Pipfile.lock
- README.md
- bin/ofparse
- docs/source/index.rst
- docs/source/ofparse.rst
- docs/source/ovs_dbg.rst
- ovs_dbg/decoders.py
- ovs_dbg/ofp.py
- ovs_dbg/ofparse/__init__.py
- ovs_dbg/ofparse/console.py
- ovs_dbg/ofparse/filter.py
- ovs_dbg/ofparse/json.py
- ovs_dbg/ofparse/logic.py
- ovs_dbg/ofparse/main.py
- ovs_dbg/ofparse/pprint.py
- setup.py
- tests/test_filter.py
Initial implementation has the following formats:
- json
- pprint (use rich to print flows with some colors)
- logic (inspired in fbl's script: use rich to print a logical tree)
> tools: Introduce ofparse tool

- bin/offline-dbg
- containers/ovs-dbg/Dockerfile
- containers/ovs-dbg/start.sh
- docs/source/index.rst
- docs/source/ofofproto.rst
> poc: add a tool to perform offline troubleshooting

- bin/ovs-lgrep
- ovs_dbg/logs.py
- setup.py
OVSLog parses lines in OVS / OVN logs and extracts the different fields
out of it.
ovs-lgrep is a very simple grepping tool that supports basic
timestamp-based selection and file interleaving
> add log parsing and simple log grepping utility

- ovs_dbg/logs.py
> lgrep: fix wrong formatting

- ovs_dbg/ofparse/console.py
> ofparse: remove debug leftovers

- ovs_dbg/ofparse/ofp.py
> ofparse: fix broken logic printing

- ovs_dbg/ofparse/process.py
> ofparse: fix json printing

- setup.py
> bump version to 0.0.9

- bin/offline-dbg
> offline-dbg: collect from sos report

- docs/source/index.rst
- docs/source/ovs-offline.rst
> docs: move ovs-offline doc file

- .gitignore
- Pipfile
- Pipfile.lock
- pyproject.toml
- setup.py
Let setuptools_scm determine the package version
> Add git-based versioning using setuptools_scm

- docs/source/index.rst
- docs/source/offline_debugging.rst
- docs/source/ofparse.rst
- docs/source/ovs-offline.rst
> docs: add tutorial for ovs-offline

- ovs_dbg/kv.py
- ovs_dbg/odp.py
- ovs_dbg/ofp.py
- ovs_dbg/ofparse/dp.py
- ovs_dbg/ofparse/ofp.py
- tests/test_filter.py
- tests/test_odp.py
- tests/test_ofp.py
That way the decoders structures are cached and performance incresased
Fixes #63
> Create openflow and datapath flows using a factory class

- .github/workflows/ci.yml
> Fix flake8 CI

- ovs_dbg/ofparse/console.py
- ovs_dbg/ofparse/ofp_logic.py
> ofparse: ensure console is started with 256 color

- containers/k8s-ofparse/Dockerfile.dev
> k8s-ofparse: clean dockerfile

- .github/workflows/ci.yml
- ovs_dbg/kv.py
- ovs_dbg/list.py
- ovs_dbg/ofparse/console.py
> Add support for python 3.6

- ovs_dbg/ofparse/dp_tree.py
Actions such as sample or check_pkt_len can also contain recirculations.
Include them in the tree
> dp_tree: support complex actions in dp_tree

- ovs_dbg/odp.py
> ofparse: properly decode tnl_pop action

- bin/ovs-offline
- containers/ovs-dbg/start.sh
> Minor fixes in ovs-offline

- ovs_dbg/odp.py
TODO: Implement proper PMD support
> odp: Work around: skip lines with pmd cpus

- ovs_dbg/odp.py
> odp: use default decoder for ports

- setup.py
> setup: pin graphviz to 0.18.2
