amorenoz/ovs-dbg

- ovs_dbg/kv.py
- ovs_dbg/list.py
Save the actual delimiters (start and end) in the metadata
> fix delimiter handling

- bin/offline-dbg
find returns 0 even if it finds zero matching files. Use ls instead
>  offline-db: fix 'find' tests 

- bin/offline-dbg
- ovs_dbg/decoders.py
- ovs_dbg/odp.py
- setup.py
- tests/test_odp.py
output_ports: can be strings, so use decode_default
geneve: can contain multiple options concatenated
geneve({...}{...})
samples: rate is a float, not int
tunnel: use masks
> Ofparse: several odp parsing fixes

- ovs_dbg/ofparse/dp.py
- ovs_dbg/ofparse/dp_graph.py
The graph code is getting bug so this PR also refactors it into it's own class.
Instead of all the flows starting and ending in the same nodes ("start" and "end"), link recirc_0 flows to their input port and link flows that output data to their output port
> Enhance datapath graph plotting by adding input and output ports

- bin/offline-dbg
- containers/ovs-dbg/start.sh
- docs/source/ofofproto.rst
Currently there are an issue preventing us from really doing OVN troubleshooting with this tool:
We can't run multiple ovsdb-server instances at the same time
This PR adds support for multiple ovsdb-servers, adds collect-db-ovn-{nb,sb} to the commandline and prints OVN hint commands nicely.
Also, it collects the OVN database from a running k8s cluster. As a result, after collecting k8s data:
```
$ ./bin/offline-dbg collect-k8s ovn_worker && ./bin/offline-dbg start
[...]
Offline OVS Debugging started                                                                                                            
******************************                                                                                                           
Working directory: /tmp/ovs-offline-dbg: …
```
> Support OVN in offline-dbg

- bin/ovs-dbg-complete
Adding ovs-dbg-complete (my intention was to add it in #41 ) allows users to quickly source all autocomplete scripts
> Add missing ovs-dbg-complete

- bin/ovs-offline
The current sos report checks a number of potential locations
for ovnnb_db and ovnsb_db. collect-sos-ovn should check each
of these locations for db files.
> offline-dbg: make collect-sos-ovn check all db locations

- ovs_dbg/ofp_act.py
- tests/test_ofp.py
Load action ususaly has the format:
load:value->dst
where "value" get's decoded as integer and "dst" as a field.
However, within the learn action it can be specified as:
load:src->dst
Where "src" is also a field.
Add support for the later format
Fixes #49 
> ofp_act: support src specification in load action

- ovs_dbg/filter.py
- tests/test_filter.py
On nested values (dictionaries) we traverse them to find the right key
for evaluation so that an expression like "key1.key2.key3=value" works.
They key is found correctly but the evaluation is performed against the
global value. Fix by making _find_data_in_kv return a tuple (kv, data)
on successful match
> Fix filtering on nested values

- ovs_dbg/ofparse/dp.py
- ovs_dbg/ofparse/dp_tree.py
When tree view (HTML or Console) is filtered, we're currently filtering individual flows beforehand which leads to:
- Missing valid flows (if the parent flow is filtered out)
- Having incomplete trees
With this PR, we first build all the subtrees and then filter out those where NONE of the subelements match the filter.
> Support subtree filtering in logic and html datapath formats

- bin/ovs-offline
- containers/ovs-dbg/start.sh
Prior to this patch, sockets created within the ovs-dbg
containers were owned by root by default.
This patch ensures the current user has permission to run
commands again and remove all sockets.
Fixes: #45
> ovs-offline: handle users properly

- containers/k8s-ofparse/Dockerfile
- containers/k8s-ofparse/monitor.sh
- docs/source/index.rst
- docs/source/k8s-ofparse.rst
- docs/source/ofparse.rst
- k8s/k8s-ofparse.yaml
- ovs_dbg/ofp.py
- ovs_dbg/ofparse/console.py
- ovs_dbg/ofparse/dp.py
- ovs_dbg/ofparse/dp_tree.py
- ovs_dbg/ofparse/html.py
- ovs_dbg/ofparse/main.py
- ovs_dbg/ofparse/ofp.py
- ovs_dbg/ofparse/ofp_logic.py
- ovs_dbg/ofparse/process.py
This PR adds multi-file support to ofparse. Only some of the formats support multi-input, for instance "datapath graph" does not.
In order to test this feature, a container and some k8s deployment scripts are introduced to enable the visualization of openflow flows in a live k8s cluster.
> ofparse: Support multi-file online flow visualization

- containers/k8s-ofparse/Dockerfile.dev
- containers/k8s-ofparse/monitor.sh
- docs/source/ofparse.rst
- k8s/k8s-ofparse.yaml
- ovs_dbg/odp.py
- ovs_dbg/ofparse/ofp.py
- ovs_dbg/ofparse/ofp_logic.py
Recent OVN versions make it a bit easier to [use ovn-detrace externally](https://github.com/ovn-org/ovn/commit/d659b6538b00bd72aeca1fc5dd3a3c337ac53f37). This enables us to use ovn-detrace to query OVN about the information it has on each cookie.
This PR adds a new cookie format for openflow flows which sorts flows first by cookie and then by table. Then, uses ovn-detrace to append OVN information about each cookie.
> Extract cookie information from OVN

- bin/ovs-offline
ovs-offline start will now error correctly if ovs-offline
collect-... has not been run prior to ovs-offline start.
fixes #71
> ovs-offline: ovs-offline start check for ovs/ovn data

- bin/ovs-offline
- containers/ovs-dbg/Dockerfile
- docs/source/ovs-offline.rst
Add build time args to allow for users to specify an
ovs repo and branch to build ovs from via option flags.
Default ovs is changed from:
https://github.com/openvswitch/ovs/archive/${OVS_VERSION}.tar.gz
to:
https://github.com/openvswitch/ovs.git branch-2.15
> ovs-offline: build containers from specified ovs repo

- bin/ovs-offline
ovs-offline build cannot be run from pip install as the
directory path will not be correct.
Add a check and additional error message in the event a user
attempts this.
fixes #69
> ovs-offline: add error message to ovs-offline build

- containers/ovs-dbg/Dockerfile
- containers/ovs-dbg/start.sh
DPDK netdevs are not registered if DPDK is not initialized so creating
them fails even if we are latter going to override them with the dummy
implementation.
To make them work, just replace them manually on the DB before startup.
Fixes: #101 
> ovs-offline: fix DPDK netdevs not appearing in ofproto bridge

- bin/ovs-offline
- containers/ovs-dbg/Dockerfile
- containers/ovs-dbg/start.sh
If ovs-* / ovn-* utilities are not available locally, alias them and use
the ones shipped in the ovs-dbg container.
In order to make it work with ovn and ovs containers, we have to
sligthly refactor how the directories are organized inside the
container to make sure the default OVN_RUNDIR inside the container is
correct.
Fixes: #72 
> ovs-offline: Alias ovn/ovs utilities if not available

- bin/ovs-offline
Allow especifying a directory of an already extracted sos report. Refactor extraction code to a function that implements both "tar" and "cp" based extractions.
Fixes: #108 
> ovs-offline: collect from extracted sos report

- .github/workflows/ci.yml
- .github/workflows/pypi-test.yml
- .github/workflows/release.yml
As runners move from 20.04 to 22.04, the matrix moves to cover more latest versions and dropping 3.6.
> Updates CI to 22.04 runners

- README.md
- setup.py
It might conflict with the installed library and without the __init__.py files it seems the include system is not giving it precedence. 
Fixes #110
> Fix vendor library inclusion

- bin/ovs-offline
With the new OVN-Kubernetes interconnection scheme added in 4.14, all the nodes now have their own OVN databases and those are located in folders different from the previous location.
The sos report module `openshift_ovn` usually gathers them, but places them in the current location, so `ovs-offline` cannot find them.
This PR just adds the new path to the locations to search at while collecting OVN information from sosreport.
> Added OVN-IC path for collect-sos-ovn subcommand, so it works for OCP 4.14+
